### ISSUE TITLE
remove MSSQL Snippets from Pack

### ISSUE THREAD

**Issue by wikrie** [rbatinov/mssql-extensions-starter-pack#1]
Hi,

as MSSQL Snippets destroy the possibility to use Capital letters C D and I please remove this from the pack!!

**Comment by rbatinov** [comment]
Thanks for your comment! 

The problem is solved in version 0.3.0 of mssql snippets extension. The problematic shortcuts are now removed and Captial letters C, D, and I can be used. 
You can download the new version or let the VS Code update it automatically for you. 

Cheers,
Happy coding,

RB Projects.
